import json


def render_current_state(registry: dict) -> str:
    task = next(t for t in registry["tasks"] if t["id"] == registry["current_task"])
    rt = task["runtime"]
    rows = [
        ("CURRENT_TASK", task["id"]), ("CURRENT_VERSION", registry["current_version"]),
        ("RUNTIME_STATE", rt["state"]), ("CURRENT_ROLE", rt["current_role"]),
        ("CURRENT_PHASE", task.get("phase")), ("STATUS", task["status"]),
        ("NEXT_ROLE", task.get("next_role")), ("NEXT_PHASE", task.get("next_phase")),
        ("NEXT_ACTION", task.get("next_action")), ("PLAN_REVISION", task.get("plan_revision")),
        ("INTAKE_STATUS", task.get("intake_status")),
        ("TASK_START_AUTHORIZATION", task.get("task_start_authorization")),
        ("REVIEW_RESULT", task.get("review_result")),
        ("EXECUTION_PREPARATION", task.get("execution_preparation")),
        ("EXECUTION_PACKAGE", task.get("execution_package")),
        ("EXECUTION_STATUS", task.get("execution_status")),
        ("VALIDATION_STATUS", task.get("validation_status")),
        ("IMPERIAL_AUTHORIZATION", task.get("imperial_authorization")),
        ("IMPERIAL_ACCEPTANCE", task.get("imperial_acceptance")),
        ("LAST_ACTION", task.get("last_action")), ("BLOCKERS", task.get("blockers", [])),
        ("LAST_COMPLETED_TASK", registry["last_completed_task"]),
    ]
    dump = "\n".join(f"{key}: {json.dumps(value, ensure_ascii=False)}" for key, value in rows)
    return ("# 当前项目状态\n\n<!-- GENERATED BY IMPERIALFLOW V1; DO NOT EDIT -->\n\n"
            "本文件由 [Canonical Registry](TASK_REGISTRY.yaml) 自动生成。任务 Markdown 头部是历史快照，"
            "不再承担当下状态权威；[Runtime 使用说明](../docs/imperialflow_runtime.md)。\n\n"
            f"机器状态修订：{registry['runtime']['revision']}；最后提交时点：{registry['runtime'].get('updated_at', '迁移基线')}。\n\n"
            f"```yaml\n{dump}\n```\n\n"
            f"完整过程证据：[当前任务记录]({task['task_file'].removeprefix('governance/')})。\n\n"
            "RUNTIME_STATE 表示当前可被调用的生命周期位置；EXECUTION 不代表部门工作已完成，实际执行进度见 EXECUTION_STATUS。"
            "路由不会自动调用下一角色。旧 VOID / UNAUTHORIZED 工件持续作废。\n")
